eureka:
  client:
    register-with-eureka: true
    fetch-registry: true  
    service-url:
      #defaultzone: http://localhost:8761/eureka/
      #defaultzone: http://eureka-primary:8011/eureka/,http://eureka-secondary:8012/eureka/,http://eureka-tertiary:8013/eureka/
      defaultzone: http://localhost:8011/eureka/,http://localhost:8012/eureka/,http://localhost:8013/eureka/
  instance:
    hostname: localhost
    # Allow Eureka to recognize two apps of the same type on the same host as separate instances:
    instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}
#server:
#  port: ${PORT:${SERVER_PORT:0}}   # Select any available port if neither port nor server port are specified.

#---
#spring:
#  profiles: sentence
#server:
#  port: 8020  
#words: NotApplicable

---
spring:
  profiles: subject
words: I,You,He,She,It

---
spring:
  profiles: verb
words: ran,knew,had,saw,bought

---
spring:
  profiles: article
words: a,the

---
spring:
  profiles: adjective
words: reasonable,leaky,suspicious,ordinary,unlikely

---
spring:
  profiles: noun
words: boat,book,vote,seat,backpack,partition,groundhog

---
spring:
  profiles: cold-noun
words: icicle,refrigerator,blizzard,snowball
